# Generated by Django 6.0.5 on 2026-05-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'verbose_name_plural': 'Alerts'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['-score', '-created_at'], 'verbose_name_plural': 'Opportunities'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name_plural': 'Sources'},
        ),
        migrations.AddField(
            model_name='opportunity',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
